# Generated by Django 5.2.1 on 2025-05-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
